# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0002_auto_20191006_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_anthropometry_Height',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_anthropometry_Weight',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
