# Generated by Django 2.1.5 on 2019-10-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0003_auto_20191006_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregnancydata',
            name='anc3_investigations_CBC',
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc3_examination_FetalEcho',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_LeftUterineArteryPl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_PIGF',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_RightUterineArteryPl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_CRL',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_Centile',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_NT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_Text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_CBC',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_KFT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_LFT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
