# Generated by Django 2.1.5 on 2019-10-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0004_auto_20191013_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydata',
            name='anc1_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc2_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc3_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc4_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc5_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc6_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc7_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc8_advice_Diabetic',
            field=models.BooleanField(default=0),
        ),
    ]
