# Generated by Django 2.1.5 on 2019-11-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0005_auto_20191017_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_AbdomenPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Alcohol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Bleeding',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_CaffeineIntake',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_DrugIntake',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Fever',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_IntimatePartnerViolence',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Nausea',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Rash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_Smoking',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_History_TobaccoIntake',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_BloodSugar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_DualScreen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_GTT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_ICT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_LeftUterineArteryPl',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_Level2USG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_NtNbScan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_PIGF',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_RightUterineArteryPl',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_TFeMoreThan14Weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_advice_TfolateLessThan14Weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_anthropometry_Bmi',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_anthropometry_Height',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_anthropometry_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Clubbing',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Cyanosis',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Edema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Lcterus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Lymphadenopathy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_general_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Bp',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_ChestCVS',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_PA',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Pr',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Proteinuria',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Rr',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Temp',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_TSH',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_deranged_AfterBreakfast',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_deranged_AfterDinner',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_deranged_AfterLunch',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_deranged_Fasting',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_urineCulture_Nitrofur',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_urineCulture_PlentyFluids',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_urineCulture_Syp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_general_urineCulture_VitC',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_BloodGroup',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_GTT_1Hour',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_GTT_2Hour',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_GTT_fast',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_HIV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_HIV_switch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Hbsag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Hbsag_switch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Hemogram',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_HusbandBloodGroup',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Tsh',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineCS',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineCS_switch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineRM',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineRM_switch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Vdrl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_Vdrl_switch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_bloodSugar_Fasting',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_bloodSugar_PostPrandial',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_dualScreen_Bhcg',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_dualScreen_PAPP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_level2Usg_DoneNotDone',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_level2Usg_NormalAbnormal',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_CRL',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_Centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_DoneNotDone',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_NT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_ntnb_Text',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_FetalEcho',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HbLess10_Hplc',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HbLess10_PeripheralSmear',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HbLess10_SerumIron',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HbLess10_TAlbendazole',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HbLess10_TFeBD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_OGTT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_QuadrupleScreen',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_TcaBD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_Tetanus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_advice_TfeOD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_PA2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_BleedingSpottingPv',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_QuickeningPerceived',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_investigations_QuadrupleScreen',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_CBC',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_DFMCLLP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_GTT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_InjTetanus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_KFT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_LFT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_TFeOD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_ictNegative_InjAntiD300',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_advice_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_FetalEcho',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_PA2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_BleedingSpottingPv',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_EasyFatigability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_LeakingDischargePv',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_investigations_ICT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_investigations_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_investigations_UrineCS',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_DFMC',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_TCaBD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_TFeOD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_USG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_advice_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_CBC_HB',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_CBC_Platelets',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_CBC_TLC',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_ICT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_KFT_Creatinine',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_KFT_UREA',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_LFT_ALP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_LFT_OT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_LFT_PT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_PA2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_UrineCulture',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_BleedingSpottingPV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_AC_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_AC_cm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_AC_weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_BPD_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_BPD_cm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_BPD_weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_EFW_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_EFW_gm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_EFW_weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_FL_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_FL_cm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_FL_weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_HC_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_HC_cm',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_HC_weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_MCAPI',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_MCAPI_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_UAPI',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_UAPI_centile',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_liquor_AFI',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_USG_liquor_SLP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_DFMCLLP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_NST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_TFeCa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_advice_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_PA2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_BleedingSpottingPV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_counseling_BirthAttendant',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_counseling_ModeOfDel_LSCS',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_counseling_ModeOfDel_Vaginal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_history_counseling_Timing',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_CBC',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_KFT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_LFT',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_investigation_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_Pelvic',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_DFMCLLP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_NST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_TFeCa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_advice_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_PA2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_BleedingSpottingPV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_DFMCLLP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_TFeCa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_advice_review',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_Pa2Weeks',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_BleedingSpottingPV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_Date',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_POG',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_Constipation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_DFMCLLP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_Diabetic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_FeCa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_GeneralNutritional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_HeatBurn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_Induction',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_LegCramps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_NauseaVomiting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_advice_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_BP',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_PA',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_PR',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_Pallor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_PedalEdema',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_Weight',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_BleedingSpottingPV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_BurningMicturition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_EasyFatiguability',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_FetalMovements',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_HeadacheEpigastricPain',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_Itching',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_history_ShortnessOfBreath',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_8',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_ALPA',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_ChronicHyper',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_ChronicKidneyDisease',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_ChronicLiverDisease',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_DrugHistory',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_Others',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_SLE',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_Type2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_box',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_heatDisease_Acyanotic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_heatDisease_Cyanotic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_heatDisease_RHD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='investigations_heatDisease_RHDpost',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
