# Generated by Django 2.1.5 on 2019-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0009_auto_20191102_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydata',
            name='investigationAncComplication',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='investigationBabyOutcome',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='investigationFtPtAbortion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='investigationMod',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
