# Generated by Django 2.1.5 on 2019-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0010_auto_20191110_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineCS_switch',
        ),
        migrations.RemoveField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineRM_switch',
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='obsForA',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='obsForG',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='obsForL',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='obsForP',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
