# Generated by Django 2.1.5 on 2019-12-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0011_auto_20191216_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineCS',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_investigations_UrineRM',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
