# Generated by Django 2.1.5 on 2020-03-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0012_auto_20191216_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc1_examination_vitals_Bp',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc2_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc3_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc4_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc5_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc8_examination_BP',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
