# Generated by Django 2.1.5 on 2019-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0027_auto_20190523_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc6_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc7_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_2_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_3_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_4_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pregnancydata',
            name='anc_5_pa_2weeks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
