# Generated by Django 2.1.5 on 2019-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0028_auto_20190706_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydata',
            name='anc_1_GeneralDeranged_breakfast',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc_1_GeneralDeranged_dinner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc_1_GeneralDeranged_fasting',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pregnancydata',
            name='anc_1_GeneralDeranged_lunch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
