# Generated by Django 2.1.5 on 2019-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swasthGarbhApp', '0029_auto_20190707_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnancydata',
            name='anc3_investigation_others',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
