# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-04 14:41
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvd_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInChikitsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorInChikitsaData', to='cvd_portal.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('medicine_Image', models.TextField()),
                ('compunds', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientInChikitsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_faced', models.TextField()),
                ('next_visit', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('doctor_comments', models.TextField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientInChikitsaData', to='cvd_portal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDataForParticularMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_times_to_take_day', models.PositiveIntegerField(default=1)),
                ('number_of_times_to_take_week', models.PositiveIntegerField(default=1)),
                ('times', models.PositiveIntegerField(default=1, null=True)),
                ('extra_comments', models.CharField(max_length=100, null=True)),
                ('start_time', cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now)),
                ('time_gap', models.DecimalField(decimal_places=1, max_digits=2)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine_reminder.Medicine')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medRemData', to='cvd_portal.Patient')),
            ],
        ),
    ]
