# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
import datetime
from dateutil import tz
from cvd_portal.models import *

class PregnancyData(models.Model):

    patient_id = models.OneToOneField(Patient, on_delete=models.CASCADE, primary_key=True)
    startDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_1 = models.BooleanField(default=0)
    anc1_diabtese = models.BooleanField(default=0)
    anc1_anemia = models.BooleanField(default=0)
    anc1_hiv = models.BooleanField(default=0)
    anc1_ultrasound = models.BooleanField(default=0)
    anc1_tetnus = models.BooleanField(default=0)
    anc1_urine = models.BooleanField(default=0)
    anc1_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc1_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_2 = models.BooleanField(default=0)
    anc2_diabtese = models.BooleanField(default=0)
    anc2_anemia = models.BooleanField(default=0)
    anc2_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc2_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_3 = models.BooleanField(default=0)
    anc3_diabtese = models.BooleanField(default=0)
    anc3_anemia = models.BooleanField(default=0)
    anc3_urine = models.BooleanField(default=0)
    anc3_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc3_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_4 = models.BooleanField(default=0)
    anc4_diabtese = models.BooleanField(default=0)
    anc4_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc4_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_5 = models.BooleanField(default=0)
    anc5_diabtese = models.BooleanField(default=0)
    anc5_urine = models.BooleanField(default=0)
    anc5_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc5_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_6 = models.BooleanField(default=0)
    anc6_diabtese = models.BooleanField(default=0)
    anc6_anemia = models.BooleanField(default=0)
    anc6_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc6_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_7 = models.BooleanField(default=0)
    anc7_diabtese = models.BooleanField(default=0)
    anc7_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc7_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    anc_8 = models.BooleanField(default=0)
    anc8_diabtese = models.BooleanField(default=0)
    anc8_dueDate = CustomDateTimeField(default=datetime.datetime.now)
    anc8_safeDate = CustomDateTimeField(default=datetime.datetime.now)
    time_stamp = CustomDateTimeField(default=datetime.datetime.now)
    investigations_ChronicHyper = models.BooleanField(default=0)
    investigations_Type2 = models.BooleanField(default=0)
    investigations_ChronicLiverDisease = models.BooleanField(default=0)
    investigations_ChronicKidneyDisease = models.BooleanField(default=0)
    investigations_ALPA = models.BooleanField(default=0)
    investigations_SLE = models.BooleanField(default=0)
    investigations_heatDisease_RHD = models.BooleanField(default=0)
    investigations_heatDisease_RHDpost = models.BooleanField(default=0)
    investigations_heatDisease_Acyanotic = models.BooleanField(default=0)
    investigations_heatDisease_Cyanotic = models.BooleanField(default=0)
    anc3_advice_review = models.BooleanField(default=0)
    anc4_advice_review = models.BooleanField(default=0)
    anc5_advice_review = models.BooleanField(default=0)
    anc6_advice_review = models.BooleanField(default=0)
    anc7_advice_review = models.BooleanField(default=0)
    anc1_History_Fever = models.BooleanField(default=0)
    anc1_History_Rash = models.BooleanField(default=0)
    anc1_History_Nausea = models.BooleanField(default=0)
    anc1_History_Bleeding = models.BooleanField(default=0)
    anc1_History_AbdomenPain = models.BooleanField(default=0)
    anc1_History_DrugIntake = models.BooleanField(default=0)
    anc1_History_Smoking = models.BooleanField(default=0)
    anc1_History_Alcohol = models.BooleanField(default=0)
    anc1_History_TobaccoIntake = models.BooleanField(default=0)
    anc1_History_CaffeineIntake = models.BooleanField(default=0)
    anc1_History_IntimatePartnerViolence = models.BooleanField(default=0)
    anc1_examination_general_Pallor = models.BooleanField(default=0)
    anc1_examination_general_Lcterus = models.BooleanField(default=0)
    anc1_examination_general_Clubbing = models.BooleanField(default=0)
    anc1_examination_general_Cyanosis = models.BooleanField(default=0)
    anc1_examination_general_Edema = models.BooleanField(default=0)
    anc1_examination_general_Lymphadenopathy = models.BooleanField(default=0)
    anc1_examination_anthropometry_Height = models.BooleanField(default=0)
    anc1_examination_anthropometry_Weight = models.BooleanField(default=0)
    anc1_investigations_HIV = models.BooleanField(default=0)
    anc1_investigations_Hbsag = models.BooleanField(default=0)
    anc1_investigations_Vdrl = models.BooleanField(default=0)
    anc1_investigations_UrineRM = models.BooleanField(default=0)
    anc1_investigations_UrineCS = models.BooleanField(default=0)
    anc1_investigations_HIV_switch = models.BooleanField(default=0)
    anc1_investigations_Hbsag_switch = models.BooleanField(default=0)
    anc1_investigations_Vdrl_switch = models.BooleanField(default=0)
    anc1_investigations_UrineRM_switch = models.BooleanField(default=0)
    anc1_investigations_UrineCS_switch = models.BooleanField(default=0)
    anc1_investigations_ntnb_CRL = models.BooleanField(default=0)
    anc1_investigations_ntnb_NT = models.BooleanField(default=0)
    anc1_investigations_ntnb_Centile = models.BooleanField(default=0)
    anc1_investigations_ntnb_Text = models.BooleanField(default=0)
    anc1_advice_GTT = models.BooleanField(default=0)
    anc1_advice_BloodSugar = models.BooleanField(default=0)
    anc1_advice_NtNbScan = models.BooleanField(default=0)
    anc1_advice_DualScreen = models.BooleanField(default=0)
    anc1_advice_LeftUterineArteryPl = models.BooleanField(default=0)
    anc1_advice_RightUterineArteryPl = models.BooleanField(default=0)
    anc1_advice_PIGF = models.BooleanField(default=0)
    anc1_advice_ICT = models.BooleanField(default=0)
    anc1_advice_Level2USG = models.BooleanField(default=0)
    anc1_advice_GeneralNutritional = models.BooleanField(default=0)
    anc1_advice_NauseaVomiting = models.BooleanField(default=0)
    anc1_advice_HeatBurn = models.BooleanField(default=0)
    anc1_advice_Constipation = models.BooleanField(default=0)
    anc1_advice_PedalEdema = models.BooleanField(default=0)
    anc1_advice_LegCramps = models.BooleanField(default=0)
    anc1_general_BgNegICT = models.BooleanField(default=0)
    anc1_general_TSH = models.BooleanField(default=0)
    anc1_general_urineCulture_Nitrofur = models.BooleanField(default=0)
    anc1_general_urineCulture_Syp = models.BooleanField(default=0)
    anc1_general_urineCulture_VitC = models.BooleanField(default=0)
    anc1_general_urineCulture_PlentyFluids = models.BooleanField(default=0)
    anc2_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc2_history_EasyFatiguability = models.BooleanField(default=0)
    anc2_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc2_history_BleedingSpottingPv = models.BooleanField(default=0)
    anc2_history_BurningMicturition = models.BooleanField(default=0)
    anc2_history_QuickeningPerceived = models.BooleanField(default=0)
    anc2_examination_Pallor = models.BooleanField(default=0)
    anc2_examination_PedalEdema = models.BooleanField(default=0)
    anc1_advice_TfolateLessThan14Weeks = models.BooleanField(default=0)
    anc1_advice_TFeMoreThan14Weeks = models.BooleanField(default=0)
    anc2_advice_OGTT = models.BooleanField(default=0)
    anc2_advice_TfeOD = models.BooleanField(default=0)
    anc2_advice_TcaBD = models.BooleanField(default=0)
    anc2_advice_Tetanus = models.BooleanField(default=0)
    anc2_advice_QuadrupleScreen = models.BooleanField(default=0)
    anc2_advice_FetalEcho = models.BooleanField(default=0)
    anc2_advice_HbLess10_TAlbendazole = models.BooleanField(default=0)
    anc2_advice_HbLess10_TFeBD = models.BooleanField(default=0)
    anc2_advice_HbLess10_Hplc = models.BooleanField(default=0)
    anc2_advice_HbLess10_PeripheralSmear = models.BooleanField(default=0)
    anc2_advice_HbLess10_SerumIron = models.BooleanField(default=0)
    anc2_advice_GeneralNutritional = models.BooleanField(default=0)
    anc2_advice_NauseaVomiting = models.BooleanField(default=0)
    anc2_advice_HeatBurn = models.BooleanField(default=0)
    anc2_advice_Constipation = models.BooleanField(default=0)
    anc2_advice_PedalEdema = models.BooleanField(default=0)
    anc2_advice_LegCramps = models.BooleanField(default=0)
    anc3_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc3_history_EasyFatigability = models.BooleanField(default=0)
    anc3_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc3_history_BleedingSpottingPv = models.BooleanField(default=0)
    anc3_history_LeakingDischargePv = models.BooleanField(default=0)
    anc3_history_BurningMicturition = models.BooleanField(default=0)
    anc3_history_FetalMovements = models.BooleanField(default=0)
    anc3_history_Itching = models.BooleanField(default=0)
    anc3_examination_Pallor = models.BooleanField(default=0)
    anc3_examination_PedalEdema = models.BooleanField(default=0)
    anc3_investigations_UrineCS = models.BooleanField(default=0)
    anc3_investigations_ICT = models.BooleanField(default=0)
    anc3_advice_TFeOD = models.BooleanField(default=0)
    anc3_advice_DFMCLLP = models.BooleanField(default=0)
    anc3_advice_InjTetanus = models.BooleanField(default=0)
    anc3_advice_CBC = models.BooleanField(default=0)
    anc3_advice_LFT = models.BooleanField(default=0)
    anc3_advice_KFT = models.BooleanField(default=0)
    anc3_advice_GTT = models.BooleanField(default=0)
    anc3_advice_ictNegative_InjAntiD300 = models.BooleanField(default=0)
    anc3_advice_GeneralNutritional = models.BooleanField(default=0)
    anc3_advice_NauseaVomiting = models.BooleanField(default=0)
    anc3_advice_HeatBurn = models.BooleanField(default=0)
    anc3_advice_Constipation = models.BooleanField(default=0)
    anc3_advice_PedalEdema = models.BooleanField(default=0)
    anc3_advice_LegCramps = models.BooleanField(default=0)
    anc4_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc4_history_EasyFatiguability = models.BooleanField(default=0)
    anc4_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc4_history_BleedingSpottingPV = models.BooleanField(default=0)
    anc4_history_BurningMicturition = models.BooleanField(default=0)
    anc4_history_FetalMovements = models.BooleanField(default=0)
    anc4_history_Itching = models.BooleanField(default=0)
    anc4_examination_Pallor = models.BooleanField(default=0)
    anc4_examination_PedalEdema = models.BooleanField(default=0)
    anc4_advice_TFeOD = models.BooleanField(default=0)
    anc4_advice_TCaBD = models.BooleanField(default=0)
    anc4_advice_DFMC = models.BooleanField(default=0)
    anc4_advice_USG = models.BooleanField(default=0)
    anc4_advice_GeneralNutritional = models.BooleanField(default=0)
    anc4_advice_NauseaVomiting = models.BooleanField(default=0)
    anc4_advice_HeatBurn = models.BooleanField(default=0)
    anc4_advice_Constipation = models.BooleanField(default=0)
    anc4_advice_PedalEdema = models.BooleanField(default=0)
    anc4_advice_LegCramps = models.BooleanField(default=0)
    anc5_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc5_history_EasyFatiguability = models.BooleanField(default=0)
    anc5_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc5_history_BleedingSpottingPV = models.BooleanField(default=0)
    anc5_history_BurningMicturition = models.BooleanField(default=0)
    anc5_history_FetalMovements = models.BooleanField(default=0)
    anc5_history_Itching = models.BooleanField(default=0)
    anc5_history_counseling_ModeOfDel_Vaginal = models.BooleanField(default=0)
    anc5_history_counseling_ModeOfDel_LSCS = models.BooleanField(default=0)
    anc5_history_counseling_BirthAttendant = models.BooleanField(default=0)
    anc5_examination_Pallor = models.BooleanField(default=0)
    anc5_examination_PedalEdema = models.BooleanField(default=0)
    anc5_investigation_CBC = models.BooleanField(default=0)
    anc5_investigation_LFT = models.BooleanField(default=0)
    anc5_investigation_KFT = models.BooleanField(default=0)
    anc5_USG_CPR = models.BooleanField(default=0)
    anc5_advice_DFMCLLP = models.BooleanField(default=0)
    anc5_advice_TFeCa = models.BooleanField(default=0)
    anc5_advice_NST = models.BooleanField(default=0)
    anc5_advice_GeneralNutritional = models.BooleanField(default=0)
    anc5_advice_NauseaVomiting = models.BooleanField(default=0)
    anc5_advice_HeatBurn = models.BooleanField(default=0)
    anc5_advice_Constipation = models.BooleanField(default=0)
    anc5_advice_PedalEdema = models.BooleanField(default=0)
    anc5_advice_LegCramps = models.BooleanField(default=0)
    anc6_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc6_history_EasyFatiguability = models.BooleanField(default=0)
    anc6_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc6_history_BleedingSpottingPV = models.BooleanField(default=0)
    anc6_history_BurningMicturition = models.BooleanField(default=0)
    anc6_history_FetalMovements = models.BooleanField(default=0)
    anc6_history_Itching = models.BooleanField(default=0)
    anc6_examination_Pallor = models.BooleanField(default=0)
    anc6_examination_PedalEdema = models.BooleanField(default=0)
    anc6_advice_DFMCLLP = models.BooleanField(default=0)
    anc6_advice_TFeCa = models.BooleanField(default=0)
    anc6_advice_NST = models.BooleanField(default=0)
    anc6_advice_GeneralNutritional = models.BooleanField(default=0)
    anc6_advice_NauseaVomiting = models.BooleanField(default=0)
    anc6_advice_HeatBurn = models.BooleanField(default=0)
    anc6_advice_Constipation = models.BooleanField(default=0)
    anc6_advice_PedalEdema = models.BooleanField(default=0)
    anc6_advice_LegCramps = models.BooleanField(default=0)
    anc7_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc7_history_EasyFatiguability = models.BooleanField(default=0)
    anc7_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc7_history_BleedingSpottingPV = models.BooleanField(default=0)
    anc7_history_BurningMicturition = models.BooleanField(default=0)
    anc7_history_FetalMovements = models.BooleanField(default=0)
    anc7_history_Itching = models.BooleanField(default=0)
    anc7_examination_Pallor = models.BooleanField(default=0)
    anc7_examination_PedalEdema = models.BooleanField(default=0)
    anc7_advice_DFMCLLP = models.BooleanField(default=0)
    anc7_advice_TFeCa = models.BooleanField(default=0)
    anc7_advice_GeneralNutritional = models.BooleanField(default=0)
    anc7_advice_NauseaVomiting = models.BooleanField(default=0)
    anc7_advice_HeatBurn = models.BooleanField(default=0)
    anc7_advice_Constipation = models.BooleanField(default=0)
    anc7_advice_PedalEdema = models.BooleanField(default=0)
    anc7_advice_LegCramps = models.BooleanField(default=0)
    anc8_history_ShortnessOfBreath = models.BooleanField(default=0)
    anc8_history_EasyFatiguability = models.BooleanField(default=0)
    anc8_history_HeadacheEpigastricPain = models.BooleanField(default=0)
    anc8_history_BleedingSpottingPV = models.BooleanField(default=0)
    anc8_history_BurningMicturition = models.BooleanField(default=0)
    anc8_history_FetalMovements = models.BooleanField(default=0)
    anc8_history_Itching = models.BooleanField(default=0)
    anc8_examination_Pallor = models.BooleanField(default=0)
    anc8_examination_PedalEdema = models.BooleanField(default=0)
    anc8_examination_PA = models.BooleanField(default=0)
    anc8_advice_DFMCLLP = models.BooleanField(default=0)
    anc8_advice_FeCa = models.BooleanField(default=0)
    anc8_advice_Induction = models.BooleanField(default=0)
    anc8_advice_GeneralNutritional = models.BooleanField(default=0)
    anc8_advice_NauseaVomiting = models.BooleanField(default=0)
    anc8_advice_HeatBurn = models.BooleanField(default=0)
    anc8_advice_Constipation = models.BooleanField(default=0)
    anc8_advice_PedalEdema = models.BooleanField(default=0)
    anc8_advice_LegCramps = models.BooleanField(default=0)
    anc_1 = models.BooleanField(default=0)
    anc_2 = models.BooleanField(default=0)
    anc_3 = models.BooleanField(default=0)
    anc_4 = models.BooleanField(default=0)
    anc_5 = models.BooleanField(default=0)
    anc_6 = models.BooleanField(default=0)
    anc_7 = models.BooleanField(default=0)
    anc_8 = models.BooleanField(default=0)
    investigations_box = models.BooleanField(default=0)
    investigations_Others = models.CharField(max_length= 100, default="", blank=True)
    investigations_DrugHistory = models.CharField(max_length= 100, default="", blank=True)
    anc1_Date = models.CharField(max_length= 100, default="", blank=True)
    anc1_POG = models.CharField(max_length= 100, default="", blank=True)
    anc1_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_anthropometry_Bmi = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_Pr = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_Bp = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_Rr = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_Temp = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_ChestCVS = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_PA = models.CharField(max_length= 100, default="", blank=True)
    anc1_examination_vitals_Proteinuria = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_BloodGroup = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_HusbandBloodGroup = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_Hemogram = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_Tsh = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_GTT_fast = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_GTT_1Hour = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_GTT_2Hour = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_bloodSugar_Fasting = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_bloodSugar_PostPrandial = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_ntnb_DoneNotDone = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_dualScreen_PAPP = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_dualScreen_Bhcg = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_level2Usg_DoneNotDone = models.CharField(max_length= 100, default="", blank=True)
    anc1_investigations_level2Usg_NormalAbnormal = models.CharField(max_length= 100, default="", blank=True)
    anc1_general_deranged_Fasting = models.CharField(max_length= 100, default="", blank=True)
    anc1_general_deranged_AfterBreakfast = models.CharField(max_length= 100, default="", blank=True)
    anc1_general_deranged_AfterLunch = models.CharField(max_length= 100, default="", blank=True)
    anc1_general_deranged_AfterDinner = models.CharField(max_length= 100, default="", blank=True)
    anc1_general_Others = models.CharField(max_length= 100, default="", blank=True)
    anc2_Date = models.CharField(max_length= 100, default="", blank=True)
    anc2_POG = models.CharField(max_length= 100, default="", blank=True)
    anc2_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc2_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc2_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc2_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc2_examination_PA2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc2_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc2_investigations_QuadrupleScreen = models.CharField(max_length= 100, default="", blank=True)
    anc2_advice_Others = models.CharField(max_length= 100, default="", blank=True)
    anc3_Date = models.CharField(max_length= 100, default="", blank=True)
    anc3_POG = models.CharField(max_length= 100, default="", blank=True)
    anc3_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc3_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc3_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc3_examination_PA2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc3_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc3_investigations_CBC = models.CharField(max_length= 100, default="", blank=True)
    anc3_investigations_Others = models.CharField(max_length= 100, default="", blank=True)
    anc4_Date = models.CharField(max_length= 100, default="", blank=True)
    anc4_POG = models.CharField(max_length= 100, default="", blank=True)
    anc4_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_PA2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_UrineCulture = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_ICT = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_CBC_HB = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_CBC_TLC = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_CBC_Platelets = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_LFT_OT = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_LFT_PT = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_LFT_ALP = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_KFT_UREA = models.CharField(max_length= 100, default="", blank=True)
    anc4_examination_KFT_Creatinine = models.CharField(max_length= 100, default="", blank=True)
    anc4_advice_Others = models.CharField(max_length= 100, default="", blank=True)
    anc5_Date = models.CharField(max_length= 100, default="", blank=True)
    anc5_POG = models.CharField(max_length= 100, default="", blank=True)
    anc5_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc5_history_counseling_Timing = models.CharField(max_length= 100, default="", blank=True)
    anc5_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc5_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc5_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc5_examination_PA2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc5_investigation_Others = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_BPD_cm = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_BPD_weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_BPD_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_HC_cm = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_HC_weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_HC_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_AC_cm = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_AC_weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_AC_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_FL_cm = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_FL_weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_FL_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_EFW_gm = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_EFW_weeks = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_EFW_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_liquor_SLP = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_liquor_AFI = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_UAPI = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_UAPI_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_MCAPI = models.CharField(max_length= 100, default="", blank=True)
    anc5_USG_MCAPI_centile = models.CharField(max_length= 100, default="", blank=True)
    anc5_advice_Others = models.CharField(max_length= 100, default="", blank=True)
    anc6_Date = models.CharField(max_length= 100, default="", blank=True)
    anc6_POG = models.CharField(max_length= 100, default="", blank=True)
    anc6_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc6_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc6_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc6_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc6_examination_PA2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc6_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc6_Pelvic = models.CharField(max_length= 100, default="", blank=True)
    anc6_advice_Others = models.CharField(max_length= 100, default="", blank=True)
    anc7_Date = models.CharField(max_length= 100, default="", blank=True)
    anc7_POG = models.CharField(max_length= 100, default="", blank=True)
    anc7_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc7_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc7_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc7_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc7_examination_Pa2Weeks = models.CharField(max_length= 100, default="", blank=True)
    anc7_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc7_advice_Others = models.CharField(max_length= 100, default="", blank=True)
    anc8_Date = models.CharField(max_length= 100, default="", blank=True)
    anc8_POG = models.CharField(max_length= 100, default="", blank=True)
    anc8_history_Others = models.CharField(max_length= 100, default="", blank=True)
    anc8_examination_PR = models.CharField(max_length= 100, default="", blank=True)
    anc8_examination_BP = models.CharField(max_length= 100, default="", blank=True)
    anc8_examination_Weight = models.CharField(max_length= 100, default="", blank=True)
    anc8_examination_Others = models.CharField(max_length= 100, default="", blank=True)
    anc8_advice_Others = models.CharField(max_length= 100, default="", blank=True)



class Medicine(models.Model):
    patient_id = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        null=True
    )
    medicine_name = models.CharField(max_length=50)
    medicine_freq = models.CharField(max_length=50, default="",)
    medicine_Image = models.TextField(default="",)
    medicine_extra_comments = models.TextField(default="",)
    medicine_start = CustomDateTimeField(default=datetime.datetime.now)
    medicine_end = CustomDateTimeField(default=datetime.datetime.now)
    isSOS = models.BooleanField(default=False)

class Hospital(models.Model):
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patientsPregHospitals')
    xCoordinate = models.DecimalField(max_digits = 20, decimal_places = 15)
    yCoordinate = models.DecimalField(max_digits = 20, decimal_places = 15)

class Complication(models.Model):
    informationByDoc = models.TextField()
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name='patientsComplication')
    complicationImage = models.TextField()
    tookAction = models.BooleanField(default=0)
    informationByPatient = models.TextField()
