from rest_framework import serializers
from swasthGarbhApp.models import *
from cvd_portal.serializers import DynamicFieldsModelSerializer
from django.contrib.auth.models import User

# class PregenancyPatientsData(DynamicFieldsModelSerializer):


class MedicineSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())
    medicines = serializers.SerializerMethodField('get_medicines_data')

    class Meta:
        model = Medicine
        fields = [
            'pk',
            'patient_id',
            'medicines'
        ]

    def get_medicines_data(self, obj):
        qset = Medicine.objects.filter(patient_id=obj.pk)
        ser = MedicinePerPatientSerialzier(qset, many=True, read_only=True)
        return ser.data


class MedicinePerPatientSerialzier(DynamicFieldsModelSerializer):

    class Meta:
        model = Medicine
        fields = [
            'pk',
            'patient_id',
            'medicine_name',
            'medicine_freq',
            'medicine_extra_comments',
            'medicine_start',
            'medicine_end',
            'medicine_Image',
            'isSOS'
        ]


class HospitalSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())

    class Meta:
        model = Hospital
        fields = [
            'pk',
            'patient_id',
            'xCoordinate',
            'yCoordinate'
        ]


class ComplicationSerializer(DynamicFieldsModelSerializer):
    patient_id = serializers.PrimaryKeyRelatedField(
        queryset=Patient.objects.all())

    class Meta:
        model = Complication
        fields = [
            'pk',
            'informationByDoc',
            'patient_id',
            'complicationImage',
            'tookAction',
            'informationByPatient'
        ]


class ComplicationPerPatientSerializer(DynamicFieldsModelSerializer):
    class Meta:
        model = Complication
        fields = [
            'pk',
            'informationByDoc',
            'complicationImage',
            'tookAction',
            'informationByPatient'
        ]


class PregenancySerializer(DynamicFieldsModelSerializer):

    medicines = serializers.SerializerMethodField('get_medicines_data')
    complications = serializers.SerializerMethodField('get_complications_data')

    class Meta:
        model = PregnancyData
        fields = [
        'pk',
        'complications',
        'medicines',
        'patient_id',
        'startDate',
        'anc1_diabtese',
        'anc1_anemia',
        'anc1_hiv',
        'anc1_ultrasound',
        'anc1_tetnus',
        'anc1_urine',
        'anc1_dueDate',
        'anc1_safeDate',
        'anc2_diabtese',
        'anc2_anemia',
        'anc2_dueDate',
        'anc2_safeDate',
        'anc3_diabtese',
        'anc3_anemia',
        'anc3_urine',
        'anc3_dueDate',
        'anc3_safeDate',
        'anc4_diabtese',
        'anc4_dueDate',
        'anc4_safeDate',
        'anc5_diabtese',
        'anc5_urine',
        'anc5_dueDate',
        'anc5_safeDate',
        'anc6_diabtese',
        'anc6_anemia',
        'anc6_dueDate',
        'anc6_safeDate',
        'anc7_diabtese',
        'anc7_dueDate',
        'anc7_safeDate',
        'anc8_diabtese',
        'anc8_dueDate',
        'anc8_safeDate',
        'time_stamp',
        'anc1_advice_Diabetic',
        'anc2_advice_Diabetic',
        'anc3_advice_Diabetic',
        'anc4_advice_Diabetic',
        'anc5_advice_Diabetic',
        'anc6_advice_Diabetic',
        'anc7_advice_Diabetic',
        'anc8_advice_Diabetic',
        'investigations_ChronicHyper',
        'investigations_Type2',
        'investigations_ChronicLiverDisease',
        'investigations_ChronicKidneyDisease',
        'investigations_ALPA',
        'investigations_SLE',
        'investigations_heatDisease_RHD',
        'investigations_heatDisease_RHDpost',
        'investigations_heatDisease_Acyanotic',
        'investigations_heatDisease_Cyanotic',
        'anc3_advice_review',
        'anc4_advice_review',
        'anc5_advice_review',
        'anc6_advice_review',
        'anc7_advice_review',
        'anc1_History_Fever',
        'anc1_History_Rash',
        'anc1_History_Nausea',
        'anc1_History_Bleeding',
        'anc1_History_AbdomenPain',
        'anc1_History_DrugIntake',
        'anc1_History_Smoking',
        'anc1_History_Alcohol',
        'anc1_History_TobaccoIntake',
        'anc1_History_CaffeineIntake',
        'anc1_History_IntimatePartnerViolence',
        'anc1_examination_general_Pallor',
        'anc1_examination_general_Lcterus',
        'anc1_examination_general_Clubbing',
        'anc1_examination_general_Cyanosis',
        'anc1_examination_general_Edema',
        'anc1_examination_general_Lymphadenopathy',
        'anc1_investigations_HIV',
        'anc1_investigations_Hbsag',
        'anc1_investigations_Vdrl',
        'anc1_investigations_UrineRM',
        'anc1_investigations_UrineCS',
        'anc1_investigations_HIV_switch',
        'anc1_investigations_Hbsag_switch',
        'anc1_investigations_Vdrl_switch',
        # 'anc1_investigations_UrineRM_switch',
        # 'anc1_investigations_UrineCS_switch',
        'anc1_advice_GTT',
        'anc1_advice_BloodSugar',
        'anc1_advice_NtNbScan',
        'anc1_advice_DualScreen',
        'anc1_advice_Level2USG',
        'anc1_advice_NauseaVomiting',
        'anc1_advice_HeatBurn',
        'anc1_advice_Constipation',
        'anc1_advice_PedalEdema',
        'anc1_advice_LegCramps',
        'anc1_general_TSH',
        'anc1_general_urineCulture_Nitrofur',
        'anc1_general_urineCulture_Syp',
        'anc1_general_urineCulture_VitC',
        'anc1_general_urineCulture_PlentyFluids',
        'anc2_history_ShortnessOfBreath',
        'anc2_history_EasyFatiguability',
        'anc2_history_HeadacheEpigastricPain',
        'anc2_history_BleedingSpottingPv',
        'anc2_history_BurningMicturition',
        'anc2_history_QuickeningPerceived',
        'anc2_examination_Pallor',
        'anc2_examination_PedalEdema',
        'anc1_advice_TfolateLessThan14Weeks',
        'anc2_advice_OGTT',
        'anc2_advice_TfeOD',
        'anc2_advice_TcaBD',
        'anc2_advice_Tetanus',
        'anc2_advice_QuadrupleScreen',
        'anc2_advice_FetalEcho',
        'anc2_advice_HbLess10_TAlbendazole',
        'anc2_advice_HbLess10_TFeBD',
        'anc2_advice_HbLess10_Hplc',
        'anc2_advice_HbLess10_PeripheralSmear',
        'anc2_advice_HbLess10_SerumIron',
        'anc2_advice_GeneralNutritional',
        'anc2_advice_NauseaVomiting',
        'anc2_advice_HeatBurn',
        'anc2_advice_Constipation',
        'anc2_advice_PedalEdema',
        'anc2_advice_LegCramps',
        'anc3_history_ShortnessOfBreath',
        'anc3_history_EasyFatigability',
        'anc3_history_HeadacheEpigastricPain',
        'anc3_history_BleedingSpottingPv',
        'anc3_history_LeakingDischargePv',
        'anc3_history_BurningMicturition',
        'anc3_history_FetalMovements',
        'anc3_history_Itching',
        'anc3_examination_Pallor',
        'anc3_examination_PedalEdema',
        'anc3_advice_TFeOD',
        'anc3_advice_DFMCLLP',
        'anc3_advice_InjTetanus',
        'anc3_advice_CBC',
        'anc3_advice_LFT',
        'anc3_advice_KFT',
        'anc3_advice_GTT',
        'anc3_advice_ictNegative_InjAntiD300',
        'anc3_advice_GeneralNutritional',
        'anc3_advice_NauseaVomiting',
        'anc3_advice_HeatBurn',
        'anc3_advice_Constipation',
        'anc3_advice_PedalEdema',
        'anc3_advice_LegCramps',
        'anc4_history_ShortnessOfBreath',
        'anc4_history_EasyFatiguability',
        'anc4_history_HeadacheEpigastricPain',
        'anc4_history_BleedingSpottingPV',
        'anc4_history_BurningMicturition',
        'anc4_history_FetalMovements',
        'anc4_history_Itching',
        'anc4_examination_Pallor',
        'anc4_examination_PedalEdema',
        'anc4_advice_TFeOD',
        'anc4_advice_TCaBD',
        'anc4_advice_DFMC',
        'anc4_advice_USG',
        'anc4_advice_GeneralNutritional',
        'anc4_advice_NauseaVomiting',
        'anc4_advice_HeatBurn',
        'anc4_advice_Constipation',
        'anc4_advice_PedalEdema',
        'anc4_advice_LegCramps',
        'anc5_history_ShortnessOfBreath',
        'anc5_history_EasyFatiguability',
        'anc5_history_HeadacheEpigastricPain',
        'anc5_history_BleedingSpottingPV',
        'anc5_history_BurningMicturition',
        'anc5_history_FetalMovements',
        'anc5_history_Itching',
        'anc5_history_counseling_ModeOfDel_Vaginal',
        'anc5_history_counseling_ModeOfDel_LSCS',
        'anc5_history_counseling_BirthAttendant',
        'anc5_examination_Pallor',
        'anc5_examination_PedalEdema',
        'anc5_advice_DFMCLLP',
        'anc5_advice_TFeCa',
        'anc5_advice_NST',
        'anc5_advice_GeneralNutritional',
        'anc5_advice_NauseaVomiting',
        'anc5_advice_HeatBurn',
        'anc5_advice_Constipation',
        'anc5_advice_PedalEdema',
        'anc5_advice_LegCramps',
        'anc6_history_ShortnessOfBreath',
        'anc6_history_EasyFatiguability',
        'anc6_history_HeadacheEpigastricPain',
        'anc6_history_BleedingSpottingPV',
        'anc6_history_BurningMicturition',
        'anc6_history_FetalMovements',
        'anc6_history_Itching',
        'anc6_examination_Pallor',
        'anc6_examination_PedalEdema',
        'anc6_advice_DFMCLLP',
        'anc6_advice_TFeCa',
        'anc6_advice_NST',
        'anc6_advice_GeneralNutritional',
        'anc6_advice_NauseaVomiting',
        'anc6_advice_HeatBurn',
        'anc6_advice_Constipation',
        'anc6_advice_PedalEdema',
        'anc6_advice_LegCramps',
        'anc7_history_ShortnessOfBreath',
        'anc7_history_EasyFatiguability',
        'anc7_history_HeadacheEpigastricPain',
        'anc7_history_BleedingSpottingPV',
        'anc7_history_BurningMicturition',
        'anc7_history_FetalMovements',
        'anc7_history_Itching',
        'anc7_examination_Pallor',
        'anc7_examination_PedalEdema',
        'anc7_advice_DFMCLLP',
        'anc7_advice_TFeCa',
        'anc7_advice_GeneralNutritional',
        'anc7_advice_NauseaVomiting',
        'anc7_advice_HeatBurn',
        'anc7_advice_Constipation',
        'anc7_advice_PedalEdema',
        'anc7_advice_LegCramps',
        'anc8_history_ShortnessOfBreath',
        'anc8_history_EasyFatiguability',
        'anc8_history_HeadacheEpigastricPain',
        'anc8_history_BleedingSpottingPV',
        'anc8_history_BurningMicturition',
        'anc8_history_FetalMovements',
        'anc8_history_Itching',
        'anc8_examination_Pallor',
        'anc8_examination_PedalEdema',
        'anc8_examination_PA',
        'anc8_advice_DFMCLLP',
        'anc8_advice_FeCa',
        'anc8_advice_Induction',
        'anc8_advice_GeneralNutritional',
        'anc8_advice_NauseaVomiting',
        'anc8_advice_HeatBurn',
        'anc8_advice_Constipation',
        'anc8_advice_PedalEdema',
        'anc8_advice_LegCramps',
        'anc_1',
        'anc_2',
        'anc_3',
        'anc_4',
        'anc_5',
        'anc_6',
        'anc_7',
        'anc_8',
        'obsForG',
        'obsForA',
        'obsForP',
        'obsForL',
        'investigations_box',
        'anc1_advice_ICT',
        'anc1_advice_GeneralNutritional',
        'anc1_advice_TFeMoreThan14Weeks',
        'anc3_investigations_UrineCS',
        'anc3_investigations_ICT',
        'investigations_Others',
        'investigations_DrugHistory',
        'anc1_Date',
        'anc1_POG',
        'anc1_history_Others',
        'anc1_examination_anthropometry_Height',
        'anc1_examination_anthropometry_Weight',
        'anc1_examination_anthropometry_Bmi',
        'anc1_examination_vitals_Pr',
        'anc1_examination_vitals_Bp',
        'anc1_examination_vitals_Rr',
        'anc1_examination_vitals_Temp',
        'anc1_examination_vitals_ChestCVS',
        'anc1_examination_vitals_PA',
        'anc1_examination_vitals_Proteinuria',
        'anc1_investigations_BloodGroup',
        'anc1_investigations_HusbandBloodGroup',
        'anc1_investigations_Hemogram',
        'anc1_investigations_Tsh',
        'anc1_investigations_GTT_fast',
        'anc1_investigations_GTT_1Hour',
        'anc1_investigations_GTT_2Hour',
        'anc1_investigations_bloodSugar_Fasting',
        'anc1_investigations_bloodSugar_PostPrandial',
        'anc1_investigations_ntnb_DoneNotDone',
        'anc1_investigations_ntnb_CRL',
        'anc1_investigations_ntnb_NT',
        'anc1_investigations_ntnb_Centile',
        'anc1_investigations_ntnb_Text',
        'anc1_investigations_dualScreen_PAPP',
        'anc1_investigations_dualScreen_Bhcg',
        'anc1_investigations_level2Usg_DoneNotDone',
        'anc1_investigations_level2Usg_NormalAbnormal',
        'anc1_advice_LeftUterineArteryPl',
        'anc1_advice_RightUterineArteryPl',
        'anc1_advice_PIGF',
        'anc1_general_BgNegICT',
        'anc1_general_deranged_Fasting',
        'anc1_general_deranged_AfterBreakfast',
        'anc1_general_deranged_AfterLunch',
        'anc1_general_deranged_AfterDinner',
        'anc1_general_Others',
        'anc2_Date',
        'anc2_POG',
        'anc2_history_Others',
        'anc2_examination_PR',
        'anc2_examination_BP',
        'anc2_examination_Weight',
        'anc2_examination_PA2Weeks',
        'anc2_examination_Others',
        'anc2_investigations_QuadrupleScreen',
        'anc2_advice_Others',
        'anc3_Date',
        'anc3_POG',
        'anc3_examination_PR',
        'anc3_examination_BP',
        'anc3_examination_Weight',
        'anc3_examination_PA2Weeks',
        'anc3_examination_FetalEcho',
        'anc3_examination_Others',
        'anc3_investigations_Others',
        'anc4_Date',
        'anc4_POG',
        'anc4_history_Others',
        'anc4_examination_PR',
        'anc4_examination_BP',
        'anc4_examination_Weight',
        'anc4_examination_PA2Weeks',
        'anc4_examination_UrineCulture',
        'anc4_examination_ICT',
        'anc4_examination_CBC_HB',
        'anc4_examination_CBC_TLC',
        'anc4_examination_CBC_Platelets',
        'anc4_examination_LFT_OT',
        'anc4_examination_LFT_PT',
        'anc4_examination_LFT_ALP',
        'anc4_examination_KFT_UREA',
        'anc4_examination_KFT_Creatinine',
        'anc4_advice_Others',
        'anc5_Date',
        'anc5_POG',
        'anc5_history_Others',
        'anc5_history_counseling_Timing',
        'anc5_examination_PR',
        'anc5_examination_BP',
        'anc5_examination_Weight',
        'anc5_examination_PA2Weeks',
        'anc5_examination_Others',
        'anc5_investigation_CBC',
        'anc5_investigation_LFT',
        'anc5_investigation_KFT',
        'anc5_investigation_Others',
        'anc5_USG_BPD_cm',
        'anc5_USG_BPD_weeks',
        'anc5_USG_BPD_centile',
        'anc5_USG_HC_cm',
        'anc5_USG_HC_weeks',
        'anc5_USG_HC_centile',
        'anc5_USG_AC_cm',
        'anc5_USG_AC_weeks',
        'anc5_USG_AC_centile',
        'anc5_USG_FL_cm',
        'anc5_USG_FL_weeks',
        'anc5_USG_FL_centile',
        'anc5_USG_EFW_gm',
        'anc5_USG_EFW_weeks',
        'anc5_USG_EFW_centile',
        'anc5_USG_liquor_SLP',
        'anc5_USG_liquor_AFI',
        'anc5_USG_UAPI',
        'anc5_USG_UAPI_centile',
        'anc5_USG_MCAPI',
        'anc5_USG_MCAPI_centile',
        'anc5_USG_CPR',
        'anc5_advice_Others',
        'anc6_Date',
        'anc6_POG',
        'anc6_history_Others',
        'anc6_examination_PR',
        'anc6_examination_BP',
        'anc6_examination_Weight',
        'anc6_examination_PA2Weeks',
        'anc6_examination_Others',
        'anc6_Pelvic',
        'anc6_advice_Others',
        'anc7_Date',
        'anc7_POG',
        'anc7_history_Others',
        'anc7_examination_PR',
        'anc7_examination_BP',
        'anc7_examination_Weight',
        'anc7_examination_Pa2Weeks',
        'anc7_examination_Others',
        'anc7_advice_Others',
        'anc8_Date',
        'anc8_POG',
        'anc8_history_Others',
        'anc8_examination_PR',
        'anc8_examination_BP',
        'anc8_examination_Weight',
        'anc8_examination_Others',
        'anc8_advice_Others',
        'investigationFtPtAbortion',
        'investigationAncComplication',
        'investigationMod',
        'investigationBabyOutcome'
        ]

    def get_medicines_data(self, obj):
        qset = Medicine.objects.filter(patient_id=obj.pk)
        ser = MedicinePerPatientSerialzier(qset, many=True, read_only=True)
        return ser.data

    def get_complications_data(self, obj):
        qset = Complication.objects.filter(patient_id=obj.pk)
        ser = ComplicationPerPatientSerializer(qset, many=True, read_only=True)
        return ser.data
