# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0016_auto_20180225_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='context_of_notification',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Default Doctor', max_length=60),
        ),
    ]
