# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0018_auto_20180705_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='abdominal_pain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='bleeding_per_vaginum',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='decreased_fetal_movements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='extra_comments',
            field=models.TextField(default=b''),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='headache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='swelling_in_hands_or_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='urine_albumin',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='visual_problems',
            field=models.BooleanField(default=False),
        ),
    ]
