# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0019_auto_20181022_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='hyper_tension',
            field=models.BooleanField(default=False),
        ),
    ]
