# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0020_patientdata_hyper_tension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='extra_comments',
            field=models.TextField(default=''),
        ),
    ]
