# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0021_auto_20181022_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='bleeding_per_vaginum',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
