# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0022_auto_20181022_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extra_comments_image',
            field=models.TextField(default=''),
        ),
    ]
