# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 10:34
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0023_image_extra_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history_high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_diseases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_obesity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='history_of_preeclampsia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='lmp',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='more_than_one_baby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_or_sister_had_preeclampsia',
            field=models.BooleanField(default=False),
        ),
    ]
