# Generated by Django 2.1.3 on 2018-11-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0024_auto_20181101_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Sahil', max_length=60),
        ),
    ]
