# Generated by Django 2.1.3 on 2019-01-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0027_auto_20190123_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='byte',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
