# Generated by Django 2.1.3 on 2019-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0028_auto_20190123_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='byte',
            field=models.TextField(),
        ),
    ]
