# Generated by Django 2.1.3 on 2019-01-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0029_auto_20190123_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notification_app',
            new_name='type',
        ),
    ]
