# Generated by Django 2.1.5 on 2019-02-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0031_auto_20190202_1821'),
        ('cvd_portal', '0032_doctor_verified'),
    ]

    operations = [
    ]
