# Generated by Django 2.1.5 on 2019-05-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0035_auto_20190518_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='UHID',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
