# Generated by Django 2.1.5 on 2019-07-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0036_auto_20190518_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='extra_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
