# Generated by Django 2.1.5 on 2019-07-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvd_portal', '0041_auto_20190718_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='extra_comments',
            field=models.TextField(blank=True, default='null'),
        ),
    ]
